language: go
go:
- 1.8.3
notifications:
  slack:
    secure: Z+GFTRRGo/MOcqI3GhiCyHt0GcwtwwOarzYNLP46J5Z8bNtvrkmoyMz/VVBL84gtN+mkd2Dz+baYS//9ASeCxg9D77VVItd/T5UBy8pDrZkx+X3KrmDGFutaTzFyO5ZPJV1pFDSBEMt7XyDT2NyNtxKtB0ExRfRba8nT63vbQiGw3pvHK4zo9nFzY9W4tP7gX/ea0ysj/P1jEE/3Dq4KEMsCbleHKw5qw4jVeUhr1g+ozV+DapvT1mdNBuTjuE3/Fbon5zHivEkW/UdKjzCSDeEVLHpC3jtkMKfqlUiyDei/g3MKMOGmoe4GMjTSknvue9CWf0LBZ43nQItmQi4THKPK/UOaKLyP5bhTaHrrwUJuacyLb6LTV8fThtEFYbKH9Ba/RhJwCyKb0iRBZOmiuST1H1T+TkBC8B/Y2CWa9+6Uv7B4tOKJB7EWyEcG19Le8m9FixD3kBD7L2TkKpo3yGeK2IGxPu3v+ltdyak9XiIhGQ6qYcWsN3QXvq1zQIxCexYqXSjYo6Zsh6qiibSYV2qwrdL6ljgcFG8YdznGFoLoaERzqrIr/0NZ0O4PghWWh70DgKa+KQ3ccUalnZKDcCOZRXK7y4FQkaP/JHy59uUQTHZvteVgbB+yI9HMi01gMLfl5VuA0PsV4jTHPkTQJHCuDpp99CbRMFiGQo0oaQ4=
